name=PinkyvoltToolkit
version=0.1.0
author=Volodymyr Mykhalchuk
maintainer=Volodymyr Mykhalchuk <vmykhalchuk@gmail.com>
sentence=Set of Pinkyvolt light helping classes (DebugWire, CRC8, etc)
paragraph=DebugWire adds protocol to read target board's status flags via single pin and no time critical constraints, also very low footprint. Other classes talk for themselves.
category=Any
url=https://github.com/vmykhalchuk/PinkyvoltToolkit
architectures=avr
license=Apache-2.0